# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only
on: [push]
jobs:  
  sqaaas_job:
       runs-on: ubuntu-latest
       name: Job that triggers SQAaaS platform branch
       steps:    
         - name: SQAaaS action step 
           uses: eosc-synergy/sqaaas-assessment-action@feature/only_criteria_workflow    
           with:    
                   criteria_workflow_only: 'True'           
                   explicit_criteria_workflow: '{"criteria_workflow": [{"id": "QC.Sty","tools": [{"docs": "https://flake8.pycqa.org/","docker": {"dockerfile":"QC.Sty/pyophidia/Dockerfile"},"reporting": {"validator": "boolean","requirement_level": "RECOMMENDED"},"name": "find_oph_workflows.py","lang": "Python"}]}]}'






