# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only
on: [push]
jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform branch
    steps:
      - name: SQAaaS action step
        uses: eosc-synergy/sqaaas-assessment-action@feature/only_criteria_workflow
        with: 
           criteria_workflow_only: True
           explicit_criteria_workflow: '"criteria_workflow": [
        {
            "id": "QC.Sty",
            "tools": [
                {
                    "docs": "https://flake8.pycqa.org/",
                    "docker": {
                        "image": "pipelinecomponents/flake8:0.9.0"
                    },
                    "args": [
                        {
                            "type": "positional", "description": "Path to Python project or file/s", "value": ".", "format": "string", "selectable": True, "repeatable": True
                        },
                        {
                            "type": "optional", "description": "Comma-separated list of files or directories to exclude", "option": "--exclude", "value": "arguments.json", "format": "string", "selectable": True, "repeatable": True
                        }
                    ],
                    "reporting": {
                        "validator": "flake8",
                        "requirement_level": "REQUIRED"
                    },
                    "name": "flake8",
                    "lang": "Python"
                }
            ]
        }
    ]'
            
        
      #- run: echo "this is readable ${{explicit_criteria_workflow}}" 
