# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only
on: [push]
jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform branch
    steps:
      - name: SQAaaS action step
        uses: eosc-synergy/sqaaas-assessment-action@feature/only_criteria_workflow
        with: 
           criteria_workflow_only: True
           explicit_criteria_workflow: "{'criteria_workflow':[{'id': 'QC.Uni','tools':[{'name':'commands','docker':{'image':'sqaaas_yprov:v1.0'},'args': [{'id':'commands','type':'positional','description":'Commands','value':'python3 -m pytest -v','format':'string','selectable':true,'repeatable':true}] } ] } ]  }"
            
        
      #- run: echo "this is readable ${{explicit_criteria_workflow}}" 
