# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only
on: [push]
jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform
    steps:
      - name: SQAaaS action step
        uses: eosc-synergy/sqaaas-assessment-action@v2
        with:
             qc_uni_steps: tox_unit_step
        uses: eosc-synergy/sqaaas-step-action@v1
        with:
             name: tox_unit_step
             tool: tox
             tox_env: run_unit
